---
spring.profiles.active: default

server.port: 7799

logging.level.dev.hoon.basic.global.config: INFO

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/basic?serverTimezone=UTC&characterEncoding=UTF-8
    sub: # for Replication
      name: sub-1
      url: jdbc:mysql://localhost:3308/basic?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: username
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    generate-ddl: false
    open-in-view: true
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: false
  redis:
    host: localhost
    port: 6379

# https://springdoc.org/#modules
springdoc:
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true

## jwt Secret Key
spring.jwt.secret: 'basic-secret'