
version: "3" # 파일 규격 버전
services: # 이 항목 밑에 실행하려는 컨테이너 들을 정의
  basic-mysql-main: # 서비스 명
    image: mysql:latest # 사용할 이미지
    container_name: basic-mysql-main # 컨테이너 이름 설정
    ports:
      - "3307:3306" # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    environment: # -e 옵션
      MYSQL_ROOT_PASSWORD: "password"  # MYSQL 패스워드 설정 옵션
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - D:\data\basic\v2:/var/lib/mysql
  basic-mysql-sub: # 서비스 명
    image: mysql:latest # 사용할 이미지
    container_name: basic-mysql-sub # 컨테이너 이름 설정
    ports:
      - "3308:3306" # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    environment: # -e 옵션
      MYSQL_ROOT_PASSWORD: "password"  # MYSQL 패스워드 설정 옵션
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - D:\data\basic\sub-v2:/var/lib/mysql
  redis: # 서비스 명
    image: redis:latest # 사용할 이미지
    container_name: redis # 컨테이너 이름 설정
    ports:
      - "6379:6379" # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)